services:
  - type: web
    name: moyofy-rafasbar
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: YOUTUBE_API_KEY
        sync: false
      - key: OAUTH_CLIENT_ID
        sync: false
      - key: OAUTH_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        value: https://moyofy-rafasbar.onrender.com/oauth2callback
      - key: DEFAULT_PLAYLIST_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: moyofy-data
      mountPath: /data
      sizeGB: 0.1